services:
  mqtt-interceptor:
    build: .
    container_name: mqtt-interceptor
    restart: unless-stopped
    
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
    
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/New_York
    
    network_mode: host